---
- name: reload exports
  ansible.builtin.command:
    cmd: exportfs -ra
  changed_when: false

- name: restart nfs
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl stop nfs-server || true
    systemctl start nfs-server

- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
